sudo: required
dist: trusty
group: deprecated-2017Q4
services:
  - docker
language: go
go:
 - 1.8

before_install:
  - go get -v github.com/Masterminds/glide
  - glide install -v

script:
 - make
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      make push;
    fi
